openapi: 3.1.0
info:
  title: Pulsedive API Reference
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    email: support@pulsedive.com
  description: >
    The API allows programmatic management of resources within Pulsedive.

    Please report any discrepancies with actual API behavior to <a href="mailto:support@pulsedive.com">Pulsedive Support</a>.
externalDocs:
  url: https://pulsedive.mintlify.app
servers:
- url: https://pulsedive.com
tags:
- name: Indicators
  description: >
    Use this endpoint to research existing Indicators by ID or value.